.TH "age.scene.Rendering" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.scene.Rendering
.SH SYNOPSIS
.br
.PP
.PP
Inherits Renderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRendering\fP (\fBScene\fP \fBscene\fP)"
.br
.ti -1c
.RI "void \fBrender\fP (Graphics g)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBrenderCamera\fP (Graphics g, \fBNode\fP node)"
.br
.ti -1c
.RI "void \fBrender\fP (Graphics g, \fBNode\fP node)"
.br
.ti -1c
.RI "void \fBrenderNode\fP (Graphics g, \fBNode\fP node)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final \fBScene\fP \fBscene\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.scene\&.Rendering\&.Rendering (\fBScene\fP scene)"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.scene\&.Rendering\&.render (Graphics g)"

.SS "void age\&.scene\&.Rendering\&.render (Graphics g, \fBNode\fP node)\fC [private]\fP"

.SS "void age\&.scene\&.Rendering\&.renderCamera (Graphics g, \fBNode\fP node)\fC [private]\fP"

.SS "void age\&.scene\&.Rendering\&.renderNode (Graphics g, \fBNode\fP node)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "final \fBScene\fP age\&.scene\&.Rendering\&.scene\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
