.TH "age.gui.Flag" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.Flag
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBOX\fP"
.br
.ti -1c
.RI "\fBFRAME\fP"
.br
.ti -1c
.RI "\fBBUTTON\fP"
.br
.ti -1c
.RI "\fBCANVAS\fP"
.br
.ti -1c
.RI "\fBTITLE\fP"
.br
.ti -1c
.RI "\fBHOVERED\fP"
.br
.ti -1c
.RI "\fBHIDDEN\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "age\&.gui\&.Flag\&.BOX"

.SS "age\&.gui\&.Flag\&.BUTTON"

.SS "age\&.gui\&.Flag\&.CANVAS"

.SS "age\&.gui\&.Flag\&.FRAME"

.SS "age\&.gui\&.Flag\&.HIDDEN"

.SS "age\&.gui\&.Flag\&.HOVERED"

.SS "age\&.gui\&.Flag\&.TITLE"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
