.TH "age.task.Tasks" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.task.Tasks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBassign\fP (Port \fBport\fP)"
.br
.ti -1c
.RI "void \fBassign\fP (\fBClient\fP \fBclient\fP)"
.br
.ti -1c
.RI "void \fBassign\fP (Events events)"
.br
.ti -1c
.RI "\fBTasks\fP ()"
.br
.ti -1c
.RI "void \fBput\fP (String command)"
.br
.ti -1c
.RI "void \fBassign\fP (String command, \fBTask\fP task)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandleEvent\fP (Event e)"
.br
.ti -1c
.RI "void \fBconstruct\fP ()"
.br
.ti -1c
.RI "void \fBperform\fP (String command)"
.br
.ti -1c
.RI "void \fBtoggleFullscreen\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final List< String > \fBinbox\fP = new ArrayList<>()"
.br
.ti -1c
.RI "final List< String > \fBoutbox\fP = new ArrayList<>()"
.br
.ti -1c
.RI "final Map< String, \fBTask\fP > \fBtasks\fP = new HashMap<>()"
.br
.ti -1c
.RI "Port \fBport\fP"
.br
.ti -1c
.RI "\fBClient\fP \fBclient\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.task\&.Tasks\&.Tasks ()"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.task\&.Tasks\&.assign (\fBClient\fP client)"

.SS "void age\&.task\&.Tasks\&.assign (Events events)"

.SS "void age\&.task\&.Tasks\&.assign (Port port)"

.SS "void age\&.task\&.Tasks\&.assign (String command, \fBTask\fP task)"

.SS "void age\&.task\&.Tasks\&.construct ()\fC [private]\fP"

.SS "void age\&.task\&.Tasks\&.handleEvent (Event e)\fC [private]\fP"

.SS "void age\&.task\&.Tasks\&.perform (String command)\fC [private]\fP"

.SS "void age\&.task\&.Tasks\&.put (String command)"

.SS "void age\&.task\&.Tasks\&.shutdown ()\fC [private]\fP"

.SS "void age\&.task\&.Tasks\&.toggleFullscreen ()\fC [private]\fP"

.SS "void age\&.task\&.Tasks\&.update ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBClient\fP age\&.task\&.Tasks\&.client\fC [private]\fP"

.SS "final List<String> age\&.task\&.Tasks\&.inbox = new ArrayList<>()\fC [private]\fP"

.SS "final List<String> age\&.task\&.Tasks\&.outbox = new ArrayList<>()\fC [private]\fP"

.SS "Port age\&.task\&.Tasks\&.port\fC [private]\fP"

.SS "final Map<String, \fBTask\fP> age\&.task\&.Tasks\&.tasks = new HashMap<>()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
