.TH "age.port.Renderable" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.port.Renderable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrender\fP (\fBGraphics\fP g)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.port\&.Renderable\&.render (\fBGraphics\fP g)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
