.TH "age.log" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.log
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBLevel\fP"
.br
.RI "Enumeration of Log Levels one can choose from that can be enabled/disabled separately\&. "
.ti -1c
.RI "class \fBLog\fP"
.br
.RI "Class that provides configurable Logging capabilities\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
