.TH "age.Util" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.Util
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static final String \fBreadFile\fP (String path)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static final String age\&.Util\&.readFile (String path)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
