.TH "age.gui.VScroller" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.VScroller
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBage\&.gui\&.Widget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVScroller\fP ()"
.br
.ti -1c
.RI "void \fBassign\fP (Tasks tasks, Task taskUp, Task taskDn)"
.br
.ti -1c
.RI "void \fBset\fP (int \fBsize\fP, int \fBpage\fP, int \fBmark\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (int \fBmark\fP)"
.br
.ti -1c
.RI "\fBWidget\fP \fBhandle\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBage\&.gui\&.Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.ti -1c
.RI "float \fBy\fP ()"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "Vector2f \fBposition\fP ()"
.br
.ti -1c
.RI "Vector2f \fBdimension\fP ()"
.br
.ti -1c
.RI "\fBDock\fP \fBdock\fP ()"
.br
.ti -1c
.RI "void \fBdock\fP (\fBDock\fP dock)"
.br
.ti -1c
.RI "void \fBdock\fP (float top, float bottom, float left, float right)"
.br
.ti -1c
.RI "void \fBposition\fP (Vector2f position)"
.br
.ti -1c
.RI "void \fBposition\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpositionAdd\fP (Vector2f \fBposition\fP)"
.br
.ti -1c
.RI "void \fBpositionAdd\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBdimension\fP (Vector2f dimension)"
.br
.ti -1c
.RI "void \fBdimension\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "void \fBdimensionAdd\fP (Vector2f \fBdimension\fP)"
.br
.ti -1c
.RI "void \fBdimensionAdd\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "Set< \fBFlag\fP > \fBflags\fP ()"
.br
.ti -1c
.RI "void \fBflag\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "void \fBclear\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "boolean \fBmatch\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "\fBWidget\fP \fBparent\fP ()"
.br
.ti -1c
.RI "List< \fBWidget\fP > \fBchildren\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBWidget\fP child)"
.br
.ti -1c
.RI "void \fBadd\fP (int idx, \fBWidget\fP child)"
.br
.ti -1c
.RI "void \fBremove\fP ()"
.br
.ti -1c
.RI "void \fBtoFront\fP ()"
.br
.ti -1c
.RI "String \fBtext\fP ()"
.br
.ti -1c
.RI "void \fBtext\fP (String text)"
.br
.ti -1c
.RI "String \fBimage\fP ()"
.br
.ti -1c
.RI "void \fBimage\fP (String image)"
.br
.ti -1c
.RI "String \fBcommand\fP ()"
.br
.ti -1c
.RI "void \fBcommand\fP (String command)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBWidget\fP \fBbtnUp\fP"
.br
.ti -1c
.RI "\fBWidget\fP \fBbar\fP"
.br
.ti -1c
.RI "\fBWidget\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBWidget\fP \fBbtnDn\fP"
.br
.ti -1c
.RI "UUID \fBuuid\fP = UUID\&.randomUUID()"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBpage\fP"
.br
.ti -1c
.RI "int \fBmark\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.gui\&.VScroller\&.VScroller ()"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.gui\&.VScroller\&.assign (Tasks tasks, Task taskUp, Task taskDn)"

.SS "void age\&.gui\&.VScroller\&.create ()\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.VScroller\&.handle ()"

.SS "void age\&.gui\&.VScroller\&.set (int size, int page, int mark)"

.SS "void age\&.gui\&.VScroller\&.value (int mark)"

.SH "Member Data Documentation"
.PP 
.SS "\fBWidget\fP age\&.gui\&.VScroller\&.bar\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.VScroller\&.btnDn\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.VScroller\&.btnUp\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.VScroller\&.handle\fC [private]\fP"

.SS "int age\&.gui\&.VScroller\&.mark\fC [private]\fP"

.SS "int age\&.gui\&.VScroller\&.page\fC [private]\fP"

.SS "int age\&.gui\&.VScroller\&.size\fC [private]\fP"

.SS "UUID age\&.gui\&.VScroller\&.uuid = UUID\&.randomUUID()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
