.TH "age.scene.Camera" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.scene.Camera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (float \fBfovy\fP, float \fBnear\fP, float \fBfar\fP)"
.br
.ti -1c
.RI "void \fBset\fP (float \fBfovy\fP, float \fBnear\fP, float \fBfar\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfovy\fP"
.br
.ti -1c
.RI "float \fBnear\fP"
.br
.ti -1c
.RI "float \fBfar\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.scene\&.Camera\&.Camera (float fovy, float near, float far)"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.scene\&.Camera\&.set (float fovy, float near, float far)"

.SH "Member Data Documentation"
.PP 
.SS "float age\&.scene\&.Camera\&.far"

.SS "float age\&.scene\&.Camera\&.fovy"

.SS "float age\&.scene\&.Camera\&.near"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
