.TH "age.clock.Task" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.clock.Task
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP (int count, long nanoperiod, float dT)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.clock\&.Task\&.run (int count, long nanoperiod, float dT)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
