.TH "age.gui.Rendering" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.Rendering
.SH SYNOPSIS
.br
.PP
.PP
Inherits Renderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRendering\fP (\fBWidgets\fP \fBwidgets\fP)"
.br
.ti -1c
.RI "void \fBrender\fP (Graphics g)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBrender\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "void \fBrenderWidget\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderBox\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderFrame\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderButton\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderCanvas\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderTitle\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderHandle\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "boolean \fBrenderMultiline\fP (Graphics g, \fBWidget\fP widget)"
.br
.ti -1c
.RI "void \fBrenderChildren\fP (Graphics g, List< \fBWidget\fP > children)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final \fBWidgets\fP \fBwidgets\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.gui\&.Rendering\&.Rendering (\fBWidgets\fP widgets)"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.gui\&.Rendering\&.render (Graphics g)"

.SS "void age\&.gui\&.Rendering\&.render (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderBox (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderButton (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderCanvas (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "void age\&.gui\&.Rendering\&.renderChildren (Graphics g, List< \fBWidget\fP > children)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderFrame (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderHandle (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderMultiline (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "boolean age\&.gui\&.Rendering\&.renderTitle (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SS "void age\&.gui\&.Rendering\&.renderWidget (Graphics g, \fBWidget\fP widget)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "final \fBWidgets\fP age\&.gui\&.Rendering\&.widgets\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
