.TH "age.gui.Dock" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.Dock
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBtop\fP ()"
.br
.ti -1c
.RI "float \fBbottom\fP ()"
.br
.ti -1c
.RI "float \fBleft\fP ()"
.br
.ti -1c
.RI "float \fBright\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (\fBDock\fP dock)"
.br
.ti -1c
.RI "void \fBset\fP (float \fBleft\fP, float \fBright\fP, float \fBtop\fP, float \fBbottom\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBleft\fP = 0"
.br
.ti -1c
.RI "float \fBright\fP = 0"
.br
.ti -1c
.RI "float \fBtop\fP = 0"
.br
.ti -1c
.RI "float \fBbottom\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float age\&.gui\&.Dock\&.bottom ()"

.SS "float age\&.gui\&.Dock\&.left ()"

.SS "float age\&.gui\&.Dock\&.right ()"

.SS "void age\&.gui\&.Dock\&.set (\fBDock\fP dock)"

.SS "void age\&.gui\&.Dock\&.set (float left, float right, float top, float bottom)"

.SS "float age\&.gui\&.Dock\&.top ()"

.SH "Member Data Documentation"
.PP 
.SS "float age\&.gui\&.Dock\&.bottom = 0\fC [private]\fP"

.SS "float age\&.gui\&.Dock\&.left = 0\fC [private]\fP"

.SS "float age\&.gui\&.Dock\&.right = 0\fC [private]\fP"

.SS "float age\&.gui\&.Dock\&.top = 0\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
