.TH "age.event.Event" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Event
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP ()"
.br
.ti -1c
.RI "\fBKey\fP \fBkey\fP ()"
.br
.ti -1c
.RI "char \fBcharacter\fP ()"
.br
.ti -1c
.RI "\fBButton\fP \fBbutton\fP ()"
.br
.ti -1c
.RI "int \fBcount\fP ()"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.ti -1c
.RI "float \fBy\fP ()"
.br
.ti -1c
.RI "Vector2f \fBposition\fP ()"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "Vector2f \fBdimension\fP ()"
.br
.ti -1c
.RI "String \fBcommand\fP ()"
.br
.ti -1c
.RI "void \fBkeyPressed\fP (\fBKey\fP \fBkey\fP, char \fBcharacter\fP)"
.br
.ti -1c
.RI "void \fBkeyReleased\fP (\fBKey\fP \fBkey\fP, char \fBcharacter\fP)"
.br
.ti -1c
.RI "void \fBkeyTyped\fP (\fBKey\fP \fBkey\fP, char \fBcharacter\fP)"
.br
.ti -1c
.RI "void \fBpointerEntered\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpointerExited\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpointerMoved\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpointerPressed\fP (\fBButton\fP \fBbutton\fP, int \fBcount\fP, float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpointerClicked\fP (\fBButton\fP \fBbutton\fP, int \fBcount\fP, float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpointerReleased\fP (\fBButton\fP \fBbutton\fP, int \fBcount\fP, float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBsurfaceResized\fP (float w, float h)"
.br
.ti -1c
.RI "void \fBsurfaceCloseRequest\fP ()"
.br
.ti -1c
.RI "void \fBtaskCommand\fP (String \fBcommand\fP)"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBkeyEvent\fP (\fBType\fP \fBtype\fP, \fBKey\fP \fBkey\fP, char \fBcharacter\fP)"
.br
.ti -1c
.RI "void \fBpointerEvent\fP (\fBType\fP \fBtype\fP, \fBButton\fP \fBbutton\fP, int \fBcount\fP, float \fBx\fP, float \fBy\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP = \fBType\&.NONE\fP"
.br
.ti -1c
.RI "\fBKey\fP \fBkey\fP = \fBKey\&.NONE\fP"
.br
.ti -1c
.RI "char \fBcharacter\fP = '\\0'"
.br
.ti -1c
.RI "\fBButton\fP \fBbutton\fP = \fBButton\&.NONE\fP"
.br
.ti -1c
.RI "int \fBcount\fP = \-1"
.br
.ti -1c
.RI "Vector2f \fBposition\fP = new Vector2f()"
.br
.ti -1c
.RI "Vector2f \fBdimension\fP = new Vector2f()"
.br
.ti -1c
.RI "String \fBcommand\fP = null"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.event\&.Event\&.Event ()\fC [package]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBButton\fP age\&.event\&.Event\&.button ()"

.SS "char age\&.event\&.Event\&.character ()"

.SS "void age\&.event\&.Event\&.clear ()"

.SS "String age\&.event\&.Event\&.command ()"

.SS "int age\&.event\&.Event\&.count ()"

.SS "Vector2f age\&.event\&.Event\&.dimension ()"

.SS "float age\&.event\&.Event\&.height ()"

.SS "\fBKey\fP age\&.event\&.Event\&.key ()"

.SS "void age\&.event\&.Event\&.keyEvent (\fBType\fP type, \fBKey\fP key, char character)\fC [private]\fP"

.SS "void age\&.event\&.Event\&.keyPressed (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Event\&.keyReleased (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Event\&.keyTyped (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Event\&.pointerClicked (\fBButton\fP button, int count, float x, float y)"

.SS "void age\&.event\&.Event\&.pointerEntered (float x, float y)"

.SS "void age\&.event\&.Event\&.pointerEvent (\fBType\fP type, \fBButton\fP button, int count, float x, float y)\fC [private]\fP"

.SS "void age\&.event\&.Event\&.pointerExited (float x, float y)"

.SS "void age\&.event\&.Event\&.pointerMoved (float x, float y)"

.SS "void age\&.event\&.Event\&.pointerPressed (\fBButton\fP button, int count, float x, float y)"

.SS "void age\&.event\&.Event\&.pointerReleased (\fBButton\fP button, int count, float x, float y)"

.SS "Vector2f age\&.event\&.Event\&.position ()"

.SS "void age\&.event\&.Event\&.surfaceCloseRequest ()"

.SS "void age\&.event\&.Event\&.surfaceResized (float w, float h)"

.SS "void age\&.event\&.Event\&.taskCommand (String command)"

.SS "\fBType\fP age\&.event\&.Event\&.type ()"

.SS "float age\&.event\&.Event\&.width ()"

.SS "float age\&.event\&.Event\&.x ()"

.SS "float age\&.event\&.Event\&.y ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBButton\fP age\&.event\&.Event\&.button = \fBButton\&.NONE\fP\fC [private]\fP"

.SS "char age\&.event\&.Event\&.character = '\\0'\fC [private]\fP"

.SS "String age\&.event\&.Event\&.command = null\fC [private]\fP"

.SS "int age\&.event\&.Event\&.count = \-1\fC [private]\fP"

.SS "Vector2f age\&.event\&.Event\&.dimension = new Vector2f()\fC [private]\fP"

.SS "\fBKey\fP age\&.event\&.Event\&.key = \fBKey\&.NONE\fP\fC [private]\fP"

.SS "Vector2f age\&.event\&.Event\&.position = new Vector2f()\fC [private]\fP"

.SS "\fBType\fP age\&.event\&.Event\&.type = \fBType\&.NONE\fP\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
