.TH "age.log.Level" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.log.Level \- Enumeration of Log Levels one can choose from that can be enabled/disabled separately\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBERROR\fP"
.br
.RI "Error level literal\&. "
.ti -1c
.RI "\fBWARNING\fP"
.br
.RI "Warning level literal\&. "
.ti -1c
.RI "\fBINFO\fP"
.br
.RI "Info level literal\&. "
.ti -1c
.RI "\fBDEBUG\fP"
.br
.RI "Debug level literal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enumeration of Log Levels one can choose from that can be enabled/disabled separately\&. 
.SH "Member Data Documentation"
.PP 
.SS "age\&.log\&.Level\&.DEBUG"

.PP
Debug level literal\&. 
.SS "age\&.log\&.Level\&.ERROR"

.PP
Error level literal\&. 
.SS "age\&.log\&.Level\&.INFO"

.PP
Info level literal\&. 
.SS "age\&.log\&.Level\&.WARNING"

.PP
Warning level literal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
