.TH "age.event.Type" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Type \- Enumeration of Event Types to register to\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNONE\fP"
.br
.RI "Literal representing 'No Event'\&. "
.ti -1c
.RI "\fBKEY_PRESSED\fP"
.br
.ti -1c
.RI "\fBKEY_RELEASED\fP"
.br
.ti -1c
.RI "\fBKEY_TYPED\fP"
.br
.ti -1c
.RI "\fBPOINTER_ENTERED\fP"
.br
.ti -1c
.RI "\fBPOINTER_EXITED\fP"
.br
.ti -1c
.RI "\fBPOINTER_PRESSED\fP"
.br
.ti -1c
.RI "\fBPOINTER_RELEASED\fP"
.br
.ti -1c
.RI "\fBPOINTER_CLICKED\fP"
.br
.ti -1c
.RI "\fBPOINTER_MOVED\fP"
.br
.ti -1c
.RI "\fBSURFACE_RESIZED\fP"
.br
.ti -1c
.RI "\fBSURFACE_CLOSE_REQUEST\fP"
.br
.ti -1c
.RI "\fBTASK_COMMAND\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enumeration of Event Types to register to\&. 
.SH "Member Data Documentation"
.PP 
.SS "age\&.event\&.Type\&.KEY_PRESSED"

.SS "age\&.event\&.Type\&.KEY_RELEASED"

.SS "age\&.event\&.Type\&.KEY_TYPED"

.SS "age\&.event\&.Type\&.NONE"

.PP
Literal representing 'No Event'\&. 
.SS "age\&.event\&.Type\&.POINTER_CLICKED"

.SS "age\&.event\&.Type\&.POINTER_ENTERED"

.SS "age\&.event\&.Type\&.POINTER_EXITED"

.SS "age\&.event\&.Type\&.POINTER_MOVED"

.SS "age\&.event\&.Type\&.POINTER_PRESSED"

.SS "age\&.event\&.Type\&.POINTER_RELEASED"

.SS "age\&.event\&.Type\&.SURFACE_CLOSE_REQUEST"

.SS "age\&.event\&.Type\&.SURFACE_RESIZED"

.SS "age\&.event\&.Type\&.TASK_COMMAND"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
