.TH "age.gui.Widgets" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.Widgets
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWidgets\fP ()"
.br
.ti -1c
.RI "void \fBassign\fP (Port port)"
.br
.ti -1c
.RI "void \fBassign\fP (Events events)"
.br
.ti -1c
.RI "\fBWidget\fP \fBroot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBWidget\fP \fBroot\fP = new \fBWidget\fP()"
.br
.ti -1c
.RI "\fBHandling\fP \fBhandling\fP = new \fBHandling\fP(this)"
.br
.ti -1c
.RI "\fBRendering\fP \fBrendering\fP = new \fBRendering\fP(this)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.gui\&.Widgets\&.Widgets ()"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.gui\&.Widgets\&.assign (Events events)"

.SS "void age\&.gui\&.Widgets\&.assign (Port port)"

.SS "\fBWidget\fP age\&.gui\&.Widgets\&.root ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBHandling\fP age\&.gui\&.Widgets\&.handling = new \fBHandling\fP(this)\fC [private]\fP"

.SS "\fBRendering\fP age\&.gui\&.Widgets\&.rendering = new \fBRendering\fP(this)\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.Widgets\&.root = new \fBWidget\fP()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
