.TH "age.scene.Scene" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.scene.Scene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP \fBroot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP \fBroot\fP = new \fBNode\fP()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP age\&.scene\&.Scene\&.root ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP age\&.scene\&.Scene\&.root = new \fBNode\fP()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
