.TH "age.log.Log" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.log.Log \- Class that provides configurable Logging capabilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "method to clear all set log levels "
.ti -1c
.RI "void \fBenable\fP (\fBLevel\fP \&.\&.\&. \fBlevels\fP)"
.br
.RI "method to enable all log levels passed in "
.ti -1c
.RI "void \fBdisable\fP (\fBLevel\fP \&.\&.\&. \fBlevels\fP)"
.br
.RI "method to disable all log levels passed in "
.ti -1c
.RI "boolean \fBtrace\fP ()"
.br
.RI "property method to return the current state of the trace flag "
.ti -1c
.RI "void \fBtrace\fP (boolean trace)"
.br
.RI "property method to set the current state of the trace flag "
.ti -1c
.RI "String \fBformat\fP ()"
.br
.RI "property method to return the current format String for log entries "
.ti -1c
.RI "void \fBformat\fP (String format)"
.br
.RI "property method to set the current format String for log entries "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBconfigure\fP (String path)"
.br
.RI "This method reads a configuration file to preconfigure the logging system\&. "
.ti -1c
.RI "static \fBLog\fP \fBget\fP (String instance)"
.br
.RI "This method returns a named log instance and creates one if not existing already\&. "
.ti -1c
.RI "static void \fBlog\fP (\fBLevel\fP level, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a log message for the 'default' Log instance\&. "
.ti -1c
.RI "static void \fBinfo\fP (String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write an info message for the 'default' Log instance\&. "
.ti -1c
.RI "static void \fBwarn\fP (String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a warning message for the 'default' Log instance\&. "
.ti -1c
.RI "static void \fBerror\fP (String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write an error message for the 'default' Log instance\&. "
.ti -1c
.RI "static void \fBdebug\fP (String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a debug message for the 'default' Log instance\&. "
.ti -1c
.RI "static void \fBlog\fP (String instance, \fBLevel\fP level, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a log message for a named Log instance\&. "
.ti -1c
.RI "static void \fBinfo\fP (String instance, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write an info message for a named Log instance\&. "
.ti -1c
.RI "static void \fBwarn\fP (String instance, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a warning message for a named Log instance\&. "
.ti -1c
.RI "static void \fBerror\fP (String instance, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write an error message for a named Log instance\&. "
.ti -1c
.RI "static void \fBdebug\fP (String instance, String message, Object \&.\&.\&. params)"
.br
.RI "This method allows to write a debug message for a named Log instance\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP ()"
.br
.RI "Constructor that sets all configurable Log settings to default\&. "
.ti -1c
.RI "\fBLog\fP (\fBLog\fP parent)"
.br
.RI "Class internal private copy constructor\&. "
.ti -1c
.RI "void \fBwrite\fP (\fBLevel\fP level, String message, Object \&.\&.\&. params)"
.br
.RI "internal method to write a log message considering all configuration settings "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "boolean \fBtrace\fP = false"
.br
.RI "flag if stack trace output is enabled or not for this Log instance "
.ti -1c
.RI "Set< \fBLevel\fP > \fBlevels\fP = null"
.br
.RI "a set of Level literals that are enabled to print out log messages "
.ti -1c
.RI "String \fBformat\fP = null"
.br
.RI "the overall log entry format String "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Map< String, \fBLog\fP > \fBmap\fP = new HashMap<>()"
.br
.RI "Map that contains named log instances that can be configured independently\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that provides configurable Logging capabilities\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.log\&.Log\&.Log ()\fC [private]\fP"

.PP
Constructor that sets all configurable Log settings to default\&. 
.SS "age\&.log\&.Log\&.Log (\fBLog\fP parent)\fC [private]\fP"

.PP
Class internal private copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP the parent Log from which the settings will be copied 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void age\&.log\&.Log\&.clear ()"

.PP
method to clear all set log levels 
.SS "static void age\&.log\&.Log\&.configure (String path)\fC [static]\fP"

.PP
This method reads a configuration file to preconfigure the logging system\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The file path to the configuration file 
.RE
.PP

.SS "static void age\&.log\&.Log\&.debug (String instance, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a debug message for a named Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.debug (String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a debug message for the 'default' Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "void age\&.log\&.Log\&.disable (\fBLevel\fP \&.\&.\&. levels)"

.PP
method to disable all log levels passed in 
.PP
\fBParameters\fP
.RS 4
\fIlevels\fP the log levels passed in 
.RE
.PP

.SS "void age\&.log\&.Log\&.enable (\fBLevel\fP \&.\&.\&. levels)"

.PP
method to enable all log levels passed in 
.PP
\fBParameters\fP
.RS 4
\fIlevels\fP the log levels passed in 
.RE
.PP

.SS "static void age\&.log\&.Log\&.error (String instance, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write an error message for a named Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.error (String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write an error message for the 'default' Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "String age\&.log\&.Log\&.format ()"

.PP
property method to return the current format String for log entries 
.PP
\fBReturns\fP
.RS 4
the current format String 
.RE
.PP

.SS "void age\&.log\&.Log\&.format (String format)"

.PP
property method to set the current format String for log entries 
.PP
\fBParameters\fP
.RS 4
\fIformat\fP the future format String 
.RE
.PP

.SS "static \fBLog\fP age\&.log\&.Log\&.get (String instance)\fC [static]\fP"

.PP
This method returns a named log instance and creates one if not existing already\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance to return/create\&. a null String returns an instance named 'default' 
.RE
.PP
\fBReturns\fP
.RS 4
The Log instance 
.RE
.PP

.SS "static void age\&.log\&.Log\&.info (String instance, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write an info message for a named Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.info (String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write an info message for the 'default' Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.log (\fBLevel\fP level, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a log message for the 'default' Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP the log level to log to 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.log (String instance, \fBLevel\fP level, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a log message for a named Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance 
.br
\fIlevel\fP the log level to log to 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "boolean age\&.log\&.Log\&.trace ()"

.PP
property method to return the current state of the trace flag 
.PP
\fBReturns\fP
.RS 4
the current state of the trace flag 
.RE
.PP

.SS "void age\&.log\&.Log\&.trace (boolean trace)"

.PP
property method to set the current state of the trace flag 
.PP
\fBParameters\fP
.RS 4
\fItrace\fP the state to set 
.RE
.PP

.SS "static void age\&.log\&.Log\&.warn (String instance, String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a warning message for a named Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIinstance\fP the name of the log instance 
.br
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "static void age\&.log\&.Log\&.warn (String message, Object \&.\&.\&. params)\fC [static]\fP"

.PP
This method allows to write a warning message for the 'default' Log instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the log message which may contain String formats 
.br
\fIparams\fP the format parameters for the message String 
.RE
.PP

.SS "void age\&.log\&.Log\&.write (\fBLevel\fP level, String message, Object \&.\&.\&. params)\fC [private]\fP"

.PP
internal method to write a log message considering all configuration settings 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP the log level 
.br
\fImessage\fP the log message with possible format entries 
.br
\fIparams\fP the parameters for the formatted message String 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "String age\&.log\&.Log\&.format = null\fC [private]\fP"

.PP
the overall log entry format String 
.SS "Set<\fBLevel\fP> age\&.log\&.Log\&.levels = null\fC [private]\fP"

.PP
a set of Level literals that are enabled to print out log messages 
.SS "final Map<String, \fBLog\fP> age\&.log\&.Log\&.map = new HashMap<>()\fC [static]\fP, \fC [private]\fP"

.PP
Map that contains named log instances that can be configured independently\&. 
.SS "boolean age\&.log\&.Log\&.trace = false\fC [private]\fP"

.PP
flag if stack trace output is enabled or not for this Log instance 

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
