.TH "age.gui.Window" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.gui.Window
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBage\&.gui\&.Widget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "String \fBtitle\fP ()"
.br
.ti -1c
.RI "void \fBtitle\fP (String title)"
.br
.ti -1c
.RI "\fBWidget\fP \fBgetPage\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBage\&.gui\&.Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.ti -1c
.RI "float \fBy\fP ()"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "Vector2f \fBposition\fP ()"
.br
.ti -1c
.RI "Vector2f \fBdimension\fP ()"
.br
.ti -1c
.RI "\fBDock\fP \fBdock\fP ()"
.br
.ti -1c
.RI "void \fBdock\fP (\fBDock\fP dock)"
.br
.ti -1c
.RI "void \fBdock\fP (float top, float bottom, float left, float right)"
.br
.ti -1c
.RI "void \fBposition\fP (Vector2f position)"
.br
.ti -1c
.RI "void \fBposition\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBpositionAdd\fP (Vector2f \fBposition\fP)"
.br
.ti -1c
.RI "void \fBpositionAdd\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBdimension\fP (Vector2f dimension)"
.br
.ti -1c
.RI "void \fBdimension\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "void \fBdimensionAdd\fP (Vector2f \fBdimension\fP)"
.br
.ti -1c
.RI "void \fBdimensionAdd\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "Set< \fBFlag\fP > \fBflags\fP ()"
.br
.ti -1c
.RI "void \fBflag\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "void \fBclear\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "boolean \fBmatch\fP (\fBFlag\fP \&.\&.\&. \fBflags\fP)"
.br
.ti -1c
.RI "\fBWidget\fP \fBparent\fP ()"
.br
.ti -1c
.RI "List< \fBWidget\fP > \fBchildren\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBWidget\fP child)"
.br
.ti -1c
.RI "void \fBadd\fP (int idx, \fBWidget\fP child)"
.br
.ti -1c
.RI "void \fBremove\fP ()"
.br
.ti -1c
.RI "void \fBtoFront\fP ()"
.br
.ti -1c
.RI "String \fBtext\fP ()"
.br
.ti -1c
.RI "void \fBtext\fP (String text)"
.br
.ti -1c
.RI "String \fBimage\fP ()"
.br
.ti -1c
.RI "void \fBimage\fP (String image)"
.br
.ti -1c
.RI "String \fBcommand\fP ()"
.br
.ti -1c
.RI "void \fBcommand\fP (String command)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBconstruct\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBWidget\fP \fBtitle\fP = new \fBWidget\fP()"
.br
.ti -1c
.RI "\fBWidget\fP \fBsize\fP = new \fBWidget\fP()"
.br
.ti -1c
.RI "\fBWidget\fP \fBclose\fP = new \fBWidget\fP()"
.br
.ti -1c
.RI "\fBWidget\fP \fBpage\fP = new \fBWidget\fP()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.gui\&.Window\&.Window (\fBFlag\fP \&.\&.\&. flags)"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.gui\&.Window\&.construct ()\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.Window\&.getPage ()"

.SS "String age\&.gui\&.Window\&.title ()"

.SS "void age\&.gui\&.Window\&.title (String title)"

.SH "Member Data Documentation"
.PP 
.SS "\fBWidget\fP age\&.gui\&.Window\&.close = new \fBWidget\fP()\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.Window\&.page = new \fBWidget\fP()\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.Window\&.size = new \fBWidget\fP()\fC [private]\fP"

.SS "\fBWidget\fP age\&.gui\&.Window\&.title = new \fBWidget\fP()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
