.TH "age.Util" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.Util \- The AGE Utility class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static final String \fBreadTextFile\fP (String path)"
.br
.RI "Static utility method to load and return text read from a file located by path\&. "
.ti -1c
.RI "static final< C > C \fBreadJSonFile\fP (String path, Class< C > cls)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final ObjectMapper \fBobjectMapper\fP = new ObjectMapper()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The AGE Utility class\&. 
.SH "Member Function Documentation"
.PP 
.SS "static final< C > C age\&.Util\&.readJSonFile (String path, Class< C > cls)\fC [static]\fP"

.SS "static final String age\&.Util\&.readTextFile (String path)\fC [static]\fP"

.PP
Static utility method to load and return text read from a file located by path\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The file path String of the file to be read 
.RE
.PP
\fBReturns\fP
.RS 4
The file contents as a text String 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final ObjectMapper age\&.Util\&.objectMapper = new ObjectMapper()\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
