.TH "age.port.jogl.JOGLEventListener" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.port.jogl.JOGLEventListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits KeyListener, MouseListener, and WindowListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBassign\fP (Events \fBevents\fP)"
.br
.ti -1c
.RI "void \fBmouseClicked\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseEntered\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseExited\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmousePressed\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseReleased\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseMoved\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseDragged\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseWheelMoved\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBkeyPressed\fP (KeyEvent e)"
.br
.ti -1c
.RI "void \fBkeyReleased\fP (KeyEvent e)"
.br
.ti -1c
.RI "void \fBwindowResized\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowMoved\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowDestroyNotify\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowDestroyed\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowGainedFocus\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowLostFocus\fP (WindowEvent e)"
.br
.ti -1c
.RI "void \fBwindowRepaint\fP (WindowUpdateEvent e)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandleSurfaceCloseRequest\fP (Event e)"
.br
.ti -1c
.RI "Button \fBtranslateButton\fP (short button)"
.br
.ti -1c
.RI "Key \fBtranslateKey\fP (short key)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Events \fBevents\fP = null"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.assign (Events events)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.handleSurfaceCloseRequest (Event e)\fC [private]\fP"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.keyPressed (KeyEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.keyReleased (KeyEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseClicked (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseDragged (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseEntered (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseExited (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseMoved (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mousePressed (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseReleased (MouseEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.mouseWheelMoved (MouseEvent e)"

.SS "Button age\&.port\&.jogl\&.JOGLEventListener\&.translateButton (short button)\fC [private]\fP"

.SS "Key age\&.port\&.jogl\&.JOGLEventListener\&.translateKey (short key)\fC [private]\fP"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowDestroyed (WindowEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowDestroyNotify (WindowEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowGainedFocus (WindowEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowLostFocus (WindowEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowMoved (WindowEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowRepaint (WindowUpdateEvent e)"

.SS "void age\&.port\&.jogl\&.JOGLEventListener\&.windowResized (WindowEvent e)"

.SH "Member Data Documentation"
.PP 
.SS "Events age\&.port\&.jogl\&.JOGLEventListener\&.events = null\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
