.TH "age.clock.Clock" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.clock.Clock \- The system Clock\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (long nanoperiod, \fBTask\fP task)"
.br
.RI "Method to add a Task to be periodically triggered after a given time period has elapsed\&. "
.ti -1c
.RI "void \fBaddFPS\fP (int fps, \fBTask\fP task)"
.br
.RI "Method to add a Task to be periodically triggered after a given time period has elapsed\&. "
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "Initializes time measurement for all Alarm objects added to the Clock\&. "
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.RI "update time measurement for all Alarm objects added to the Clock, and indirectly triggers and executes Tasks when their Alarm period has elapsed\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final List< \fBAlarm\fP > \fBalarms\fP = new ArrayList<>()"
.br
.RI "The internal list to manage Alarm objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
The system Clock\&. 

Normally only one instance of that clock is created per application\&. It manages and synchronizes multiple Alarm objects that each are responsible to manage the time periodic triggering of a specific Task 
.br
 
.SH "Member Function Documentation"
.PP 
.SS "void age\&.clock\&.Clock\&.add (long nanoperiod, \fBTask\fP task)"

.PP
Method to add a Task to be periodically triggered after a given time period has elapsed\&. 
.PP
\fBParameters\fP
.RS 4
\fInanoperiod\fP the time period in nano seconds after which the Task is triggered\&. 
.br
\fItask\fP the Task to be triggered and executed\&. 
.RE
.PP

.SS "void age\&.clock\&.Clock\&.addFPS (int fps, \fBTask\fP task)"

.PP
Method to add a Task to be periodically triggered after a given time period has elapsed\&. 
.PP
\fBParameters\fP
.RS 4
\fIfps\fP the trigger frames per second (i\&. e\&. how often the Task is triggered per second) 
.br
\fItask\fP the Task to be triggered and executed\&. 
.RE
.PP

.SS "void age\&.clock\&.Clock\&.init ()"

.PP
Initializes time measurement for all Alarm objects added to the Clock\&. 
.SS "void age\&.clock\&.Clock\&.update ()"

.PP
update time measurement for all Alarm objects added to the Clock, and indirectly triggers and executes Tasks when their Alarm period has elapsed\&. 
.SH "Member Data Documentation"
.PP 
.SS "final List<\fBAlarm\fP> age\&.clock\&.Clock\&.alarms = new ArrayList<>()\fC [private]\fP"

.PP
The internal list to manage Alarm objects\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
