.TH "age.event.Handler" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Handler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBEvent\fP event)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.event\&.Handler\&.handle (\fBEvent\fP event)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
