.TH "age.event.Key" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Key \- Enumeration of Keyboard Keys\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNONE\fP"
.br
.RI "Literal representing 'No Key'\&. "
.ti -1c
.RI "\fBESCAPE\fP"
.br
.ti -1c
.RI "\fBF1\fP"
.br
.ti -1c
.RI "\fBF2\fP"
.br
.ti -1c
.RI "\fBF3\fP"
.br
.ti -1c
.RI "\fBF4\fP"
.br
.ti -1c
.RI "\fBF5\fP"
.br
.ti -1c
.RI "\fBF6\fP"
.br
.ti -1c
.RI "\fBF7\fP"
.br
.ti -1c
.RI "\fBF8\fP"
.br
.ti -1c
.RI "\fBF9\fP"
.br
.ti -1c
.RI "\fBF10\fP"
.br
.ti -1c
.RI "\fBF11\fP"
.br
.ti -1c
.RI "\fBF12\fP"
.br
.ti -1c
.RI "\fBPRINT_SCREEN\fP"
.br
.ti -1c
.RI "\fBSCROLL_LOCK\fP"
.br
.ti -1c
.RI "\fBPAUSE\fP"
.br
.ti -1c
.RI "\fB_1\fP"
.br
.ti -1c
.RI "\fB_2\fP"
.br
.ti -1c
.RI "\fB_3\fP"
.br
.ti -1c
.RI "\fB_4\fP"
.br
.ti -1c
.RI "\fB_5\fP"
.br
.ti -1c
.RI "\fB_6\fP"
.br
.ti -1c
.RI "\fB_7\fP"
.br
.ti -1c
.RI "\fB_8\fP"
.br
.ti -1c
.RI "\fB_9\fP"
.br
.ti -1c
.RI "\fB_0\fP"
.br
.ti -1c
.RI "\fBBACK_SPACE\fP"
.br
.ti -1c
.RI "\fBTAB\fP"
.br
.ti -1c
.RI "\fBENTER\fP"
.br
.ti -1c
.RI "\fBSPACE\fP"
.br
.ti -1c
.RI "\fBQ\fP"
.br
.ti -1c
.RI "\fBW\fP"
.br
.ti -1c
.RI "\fBE\fP"
.br
.ti -1c
.RI "\fBR\fP"
.br
.ti -1c
.RI "\fBT\fP"
.br
.ti -1c
.RI "\fBZ\fP"
.br
.ti -1c
.RI "\fBU\fP"
.br
.ti -1c
.RI "\fBI\fP"
.br
.ti -1c
.RI "\fBO\fP"
.br
.ti -1c
.RI "\fBP\fP"
.br
.ti -1c
.RI "\fBA\fP"
.br
.ti -1c
.RI "\fBS\fP"
.br
.ti -1c
.RI "\fBD\fP"
.br
.ti -1c
.RI "\fBF\fP"
.br
.ti -1c
.RI "\fBG\fP"
.br
.ti -1c
.RI "\fBH\fP"
.br
.ti -1c
.RI "\fBJ\fP"
.br
.ti -1c
.RI "\fBK\fP"
.br
.ti -1c
.RI "\fBL\fP"
.br
.ti -1c
.RI "\fBY\fP"
.br
.ti -1c
.RI "\fBX\fP"
.br
.ti -1c
.RI "\fBC\fP"
.br
.ti -1c
.RI "\fBV\fP"
.br
.ti -1c
.RI "\fBB\fP"
.br
.ti -1c
.RI "\fBN\fP"
.br
.ti -1c
.RI "\fBM\fP"
.br
.ti -1c
.RI "\fBPLUS\fP"
.br
.ti -1c
.RI "\fBMINUS\fP"
.br
.ti -1c
.RI "\fBCAPS_LOCK\fP"
.br
.ti -1c
.RI "\fBSHIFT\fP"
.br
.ti -1c
.RI "\fBCONTROL\fP"
.br
.ti -1c
.RI "\fBSYSTEM\fP"
.br
.ti -1c
.RI "\fBALT\fP"
.br
.ti -1c
.RI "\fBMENU\fP"
.br
.ti -1c
.RI "\fBINSERT\fP"
.br
.ti -1c
.RI "\fBDELETE\fP"
.br
.ti -1c
.RI "\fBPOS1\fP"
.br
.ti -1c
.RI "\fBEND\fP"
.br
.ti -1c
.RI "\fBPAGE_UP\fP"
.br
.ti -1c
.RI "\fBPAGE_DOWN\fP"
.br
.ti -1c
.RI "\fBUP\fP"
.br
.ti -1c
.RI "\fBDOWN\fP"
.br
.ti -1c
.RI "\fBLEFT\fP"
.br
.ti -1c
.RI "\fBRIGHT\fP"
.br
.ti -1c
.RI "\fBNUM_LOCK\fP"
.br
.ti -1c
.RI "\fBDIVIDE\fP"
.br
.ti -1c
.RI "\fBMULTIPLY\fP"
.br
.ti -1c
.RI "\fBSUBTRACT\fP"
.br
.ti -1c
.RI "\fBADD\fP"
.br
.ti -1c
.RI "\fBDECIMAL\fP"
.br
.ti -1c
.RI "\fBNP_7\fP"
.br
.ti -1c
.RI "\fBNP_8\fP"
.br
.ti -1c
.RI "\fBNP_9\fP"
.br
.ti -1c
.RI "\fBNP_4\fP"
.br
.ti -1c
.RI "\fBNP_5\fP"
.br
.ti -1c
.RI "\fBNP_6\fP"
.br
.ti -1c
.RI "\fBNP_1\fP"
.br
.ti -1c
.RI "\fBNP_2\fP"
.br
.ti -1c
.RI "\fBNP_3\fP"
.br
.ti -1c
.RI "\fBNP_0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enumeration of Keyboard Keys\&. 
.SH "Member Data Documentation"
.PP 
.SS "age\&.event\&.Key\&._0"

.SS "age\&.event\&.Key\&._1"

.SS "age\&.event\&.Key\&._2"

.SS "age\&.event\&.Key\&._3"

.SS "age\&.event\&.Key\&._4"

.SS "age\&.event\&.Key\&._5"

.SS "age\&.event\&.Key\&._6"

.SS "age\&.event\&.Key\&._7"

.SS "age\&.event\&.Key\&._8"

.SS "age\&.event\&.Key\&._9"

.SS "age\&.event\&.Key\&.A"

.SS "age\&.event\&.Key\&.ADD"

.SS "age\&.event\&.Key\&.ALT"

.SS "age\&.event\&.Key\&.B"

.SS "age\&.event\&.Key\&.BACK_SPACE"

.SS "age\&.event\&.Key\&.C"

.SS "age\&.event\&.Key\&.CAPS_LOCK"

.SS "age\&.event\&.Key\&.CONTROL"

.SS "age\&.event\&.Key\&.D"

.SS "age\&.event\&.Key\&.DECIMAL"

.SS "age\&.event\&.Key\&.DELETE"

.SS "age\&.event\&.Key\&.DIVIDE"

.SS "age\&.event\&.Key\&.DOWN"

.SS "age\&.event\&.Key\&.E"

.SS "age\&.event\&.Key\&.END"

.SS "age\&.event\&.Key\&.ENTER"

.SS "age\&.event\&.Key\&.ESCAPE"

.SS "age\&.event\&.Key\&.F"

.SS "age\&.event\&.Key\&.F1"

.SS "age\&.event\&.Key\&.F10"

.SS "age\&.event\&.Key\&.F11"

.SS "age\&.event\&.Key\&.F12"

.SS "age\&.event\&.Key\&.F2"

.SS "age\&.event\&.Key\&.F3"

.SS "age\&.event\&.Key\&.F4"

.SS "age\&.event\&.Key\&.F5"

.SS "age\&.event\&.Key\&.F6"

.SS "age\&.event\&.Key\&.F7"

.SS "age\&.event\&.Key\&.F8"

.SS "age\&.event\&.Key\&.F9"

.SS "age\&.event\&.Key\&.G"

.SS "age\&.event\&.Key\&.H"

.SS "age\&.event\&.Key\&.I"

.SS "age\&.event\&.Key\&.INSERT"

.SS "age\&.event\&.Key\&.J"

.SS "age\&.event\&.Key\&.K"

.SS "age\&.event\&.Key\&.L"

.SS "age\&.event\&.Key\&.LEFT"

.SS "age\&.event\&.Key\&.M"

.SS "age\&.event\&.Key\&.MENU"

.SS "age\&.event\&.Key\&.MINUS"

.SS "age\&.event\&.Key\&.MULTIPLY"

.SS "age\&.event\&.Key\&.N"

.SS "age\&.event\&.Key\&.NONE"

.PP
Literal representing 'No Key'\&. 
.SS "age\&.event\&.Key\&.NP_0"

.SS "age\&.event\&.Key\&.NP_1"

.SS "age\&.event\&.Key\&.NP_2"

.SS "age\&.event\&.Key\&.NP_3"

.SS "age\&.event\&.Key\&.NP_4"

.SS "age\&.event\&.Key\&.NP_5"

.SS "age\&.event\&.Key\&.NP_6"

.SS "age\&.event\&.Key\&.NP_7"

.SS "age\&.event\&.Key\&.NP_8"

.SS "age\&.event\&.Key\&.NP_9"

.SS "age\&.event\&.Key\&.NUM_LOCK"

.SS "age\&.event\&.Key\&.O"

.SS "age\&.event\&.Key\&.P"

.SS "age\&.event\&.Key\&.PAGE_DOWN"

.SS "age\&.event\&.Key\&.PAGE_UP"

.SS "age\&.event\&.Key\&.PAUSE"

.SS "age\&.event\&.Key\&.PLUS"

.SS "age\&.event\&.Key\&.POS1"

.SS "age\&.event\&.Key\&.PRINT_SCREEN"

.SS "age\&.event\&.Key\&.Q"

.SS "age\&.event\&.Key\&.R"

.SS "age\&.event\&.Key\&.RIGHT"

.SS "age\&.event\&.Key\&.S"

.SS "age\&.event\&.Key\&.SCROLL_LOCK"

.SS "age\&.event\&.Key\&.SHIFT"

.SS "age\&.event\&.Key\&.SPACE"

.SS "age\&.event\&.Key\&.SUBTRACT"

.SS "age\&.event\&.Key\&.SYSTEM"

.SS "age\&.event\&.Key\&.T"

.SS "age\&.event\&.Key\&.TAB"

.SS "age\&.event\&.Key\&.U"

.SS "age\&.event\&.Key\&.UP"

.SS "age\&.event\&.Key\&.V"

.SS "age\&.event\&.Key\&.W"

.SS "age\&.event\&.Key\&.X"

.SS "age\&.event\&.Key\&.Y"

.SS "age\&.event\&.Key\&.Z"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
