.TH "age.event.Button" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Button
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNONE\fP"
.br
.ti -1c
.RI "\fBBTN1\fP"
.br
.ti -1c
.RI "\fBBTN2\fP"
.br
.ti -1c
.RI "\fBBTN3\fP"
.br
.ti -1c
.RI "\fBBTN4\fP"
.br
.ti -1c
.RI "\fBBTN5\fP"
.br
.ti -1c
.RI "\fBBTN6\fP"
.br
.ti -1c
.RI "\fBBTN7\fP"
.br
.ti -1c
.RI "\fBBTN8\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "age\&.event\&.Button\&.BTN1"

.SS "age\&.event\&.Button\&.BTN2"

.SS "age\&.event\&.Button\&.BTN3"

.SS "age\&.event\&.Button\&.BTN4"

.SS "age\&.event\&.Button\&.BTN5"

.SS "age\&.event\&.Button\&.BTN6"

.SS "age\&.event\&.Button\&.BTN7"

.SS "age\&.event\&.Button\&.BTN8"

.SS "age\&.event\&.Button\&.NONE"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
