.TH "age.log.Level" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.log.Level
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBERROR\fP"
.br
.ti -1c
.RI "\fBWARNING\fP"
.br
.ti -1c
.RI "\fBINFO\fP"
.br
.ti -1c
.RI "\fBDEBUG\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "age\&.log\&.Level\&.DEBUG"

.SS "age\&.log\&.Level\&.ERROR"

.SS "age\&.log\&.Level\&.INFO"

.SS "age\&.log\&.Level\&.WARNING"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
