.TH "age.scene.Part" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.scene.Part
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheck\fP (Object object)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTRANSFORM\fP =(Matrix4f\&.class)"
.br
.ti -1c
.RI "\fBCAMERA\fP =(Camera\&.class)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBPart\fP (Class<?> \fBcls\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Class<?> \fBcls\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.scene\&.Part\&.Part (Class<?> cls)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.scene\&.Part\&.check (Object object)"

.SH "Member Data Documentation"
.PP 
.SS "age\&.scene\&.Part\&.CAMERA =(Camera\&.class)"

.SS "Class<?> age\&.scene\&.Part\&.cls\fC [private]\fP"

.SS "age\&.scene\&.Part\&.TRANSFORM =(Matrix4f\&.class)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
