.TH "age.event" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBButton\fP"
.br
.RI "Enumeration of Pointer Buttons\&. "
.ti -1c
.RI "class \fBEvent\fP"
.br
.RI "This class defines an Event along with its descriptive data\&. "
.ti -1c
.RI "class \fBEvents\fP"
.br
.ti -1c
.RI "interface \fBHandler\fP"
.br
.RI "Interface to define an event handler method reference\&. "
.ti -1c
.RI "enum \fBKey\fP"
.br
.RI "Enumeration of Keyboard Keys\&. "
.ti -1c
.RI "enum \fBType\fP"
.br
.RI "Enumeration of Event Types to register to\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
