.TH "age.event.Events" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Events
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBassign\fP (\fBType\fP type, \fBHandler\fP handler)"
.br
.ti -1c
.RI "void \fBpostKeyPressed\fP (\fBKey\fP key, char character)"
.br
.ti -1c
.RI "void \fBpostKeyReleased\fP (\fBKey\fP key, char character)"
.br
.ti -1c
.RI "void \fBpostKeyTyped\fP (\fBKey\fP key, char character)"
.br
.ti -1c
.RI "void \fBpostPointerEntered\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBpostPointerExited\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBpostPointerMoved\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBpostPointerPressed\fP (\fBButton\fP button, int count, float x, float y)"
.br
.ti -1c
.RI "void \fBpostPointerReleased\fP (\fBButton\fP button, int count, float x, float y)"
.br
.ti -1c
.RI "void \fBpostPointerClicked\fP (\fBButton\fP button, int count, float x, float y)"
.br
.ti -1c
.RI "void \fBpostSurfaceResized\fP (float w, float h)"
.br
.ti -1c
.RI "void \fBpostSurfaceCloseRequest\fP ()"
.br
.ti -1c
.RI "void \fBpostTaskCommand\fP (String command)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBEvent\fP event)"
.br
.ti -1c
.RI "void \fBpost\fP (\fBEvent\fP event)"
.br
.ti -1c
.RI "\fBEvent\fP \fBalloc\fP ()"
.br
.ti -1c
.RI "void \fBfree\fP (\fBEvent\fP event)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final Queue< \fBEvent\fP > \fBcache\fP = new LinkedList<>()"
.br
.ti -1c
.RI "final List< \fBEvent\fP > \fBinbox\fP = new ArrayList<>()"
.br
.ti -1c
.RI "final List< \fBEvent\fP > \fBoutbox\fP = new ArrayList<>()"
.br
.ti -1c
.RI "final Map< \fBType\fP, List< \fBHandler\fP > > \fBhandlers\fP = new EnumMap<>(Type\&.class)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBEvent\fP age\&.event\&.Events\&.alloc ()\fC [private]\fP"

.SS "void age\&.event\&.Events\&.assign (\fBType\fP type, \fBHandler\fP handler)"

.SS "void age\&.event\&.Events\&.free (\fBEvent\fP event)\fC [private]\fP"

.SS "void age\&.event\&.Events\&.handle (\fBEvent\fP event)\fC [private]\fP"

.SS "void age\&.event\&.Events\&.post (\fBEvent\fP event)\fC [private]\fP"

.SS "void age\&.event\&.Events\&.postKeyPressed (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Events\&.postKeyReleased (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Events\&.postKeyTyped (\fBKey\fP key, char character)"

.SS "void age\&.event\&.Events\&.postPointerClicked (\fBButton\fP button, int count, float x, float y)"

.SS "void age\&.event\&.Events\&.postPointerEntered (float x, float y)"

.SS "void age\&.event\&.Events\&.postPointerExited (float x, float y)"

.SS "void age\&.event\&.Events\&.postPointerMoved (float x, float y)"

.SS "void age\&.event\&.Events\&.postPointerPressed (\fBButton\fP button, int count, float x, float y)"

.SS "void age\&.event\&.Events\&.postPointerReleased (\fBButton\fP button, int count, float x, float y)"

.SS "void age\&.event\&.Events\&.postSurfaceCloseRequest ()"

.SS "void age\&.event\&.Events\&.postSurfaceResized (float w, float h)"

.SS "void age\&.event\&.Events\&.postTaskCommand (String command)"

.SS "void age\&.event\&.Events\&.update ()"

.SH "Member Data Documentation"
.PP 
.SS "final Queue<\fBEvent\fP> age\&.event\&.Events\&.cache = new LinkedList<>()\fC [private]\fP"

.SS "final Map<\fBType\fP, List<\fBHandler\fP> > age\&.event\&.Events\&.handlers = new EnumMap<>(Type\&.class)\fC [private]\fP"

.SS "final List<\fBEvent\fP> age\&.event\&.Events\&.inbox = new ArrayList<>()\fC [private]\fP"

.SS "final List<\fBEvent\fP> age\&.event\&.Events\&.outbox = new ArrayList<>()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
