.TH "age.clock.Alarm" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.clock.Alarm \- This package visible class represents a single alarm schedule that periodically triggers a Task after a preset time period 
.br
  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (long nanotime)"
.br
.RI "Initializes the time measurement for this Alarm object\&. "
.ti -1c
.RI "void \fBupdate\fP (long nanotime)"
.br
.RI "Updates the time measurement for this Alarm object and periodically triggers the Task after the time period has elapsed\&. "
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBAlarm\fP (long \fBnanoperiod\fP, \fBTask\fP \fBtask\fP)"
.br
.RI "Package visible constructor\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBtrigger\fP (int count, float dT)"
.br
.RI "Internal method that is called when the time period has elapsed and the task is to be triggered by this method\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "long \fBnanoperiod\fP"
.br
.RI "The time period between triggers in nano seconds\&. "
.ti -1c
.RI "\fBTask\fP \fBtask\fP"
.br
.RI "The task that is triggered periodically after each nanoperiod\&. "
.ti -1c
.RI "long \fBmark\fP"
.br
.RI "The time mark in nanoseconds to measure when a period elapses 
.br
 "
.in -1c
.SH "Detailed Description"
.PP 
This package visible class represents a single alarm schedule that periodically triggers a Task after a preset time period 
.br
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.clock\&.Alarm\&.Alarm (long nanoperiod, \fBTask\fP task)\fC [package]\fP"

.PP
Package visible constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fInanoperiod\fP the time period in nano seconds after which periodically the task is triggered 
.br
\fItask\fP the task that is triggered periodically each time the nanoperiod time has elapsed 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void age\&.clock\&.Alarm\&.init (long nanotime)"

.PP
Initializes the time measurement for this Alarm object\&. 
.PP
\fBParameters\fP
.RS 4
\fInanotime\fP the current system time stamp in nano precision 
.RE
.PP

.SS "void age\&.clock\&.Alarm\&.trigger (int count, float dT)\fC [private]\fP"

.PP
Internal method that is called when the time period has elapsed and the task is to be triggered by this method\&. 
.PP
\fBParameters\fP
.RS 4
\fIcount\fP the count of full time periods that did elapse since the last time the Task has been triggered\&. Normally the count is 1\&. 
.br
\fIdT\fP the time in seconds since the last time the Task has been triggered\&. 
.RE
.PP

.SS "void age\&.clock\&.Alarm\&.update (long nanotime)"

.PP
Updates the time measurement for this Alarm object and periodically triggers the Task after the time period has elapsed\&. 
.PP
\fBParameters\fP
.RS 4
\fInanotime\fP the current system time stamp in nano precision 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "long age\&.clock\&.Alarm\&.mark\fC [private]\fP"

.PP
The time mark in nanoseconds to measure when a period elapses 
.br
 
.SS "long age\&.clock\&.Alarm\&.nanoperiod\fC [private]\fP"

.PP
The time period between triggers in nano seconds\&. 
.SS "\fBTask\fP age\&.clock\&.Alarm\&.task\fC [private]\fP"

.PP
The task that is triggered periodically after each nanoperiod\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
