.TH "age.clock.Clock" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.clock.Clock
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (long nanoperiod, \fBTask\fP task)"
.br
.ti -1c
.RI "void \fBaddFPS\fP (int fps, \fBTask\fP task)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final List< \fBAlarm\fP > \fBalarms\fP = new ArrayList<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.clock\&.Clock\&.add (long nanoperiod, \fBTask\fP task)"

.SS "void age\&.clock\&.Clock\&.addFPS (int fps, \fBTask\fP task)"

.SS "void age\&.clock\&.Clock\&.init ()"

.SS "void age\&.clock\&.Clock\&.update ()"

.SH "Member Data Documentation"
.PP 
.SS "final List<\fBAlarm\fP> age\&.clock\&.Clock\&.alarms = new ArrayList<>()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
