.TH "age.event.Handler" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Handler \- Interface to define an event handler method reference\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBEvent\fP event)"
.br
.RI "The event handler method reference definition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface to define an event handler method reference\&. 
.SH "Member Function Documentation"
.PP 
.SS "void age\&.event\&.Handler\&.handle (\fBEvent\fP event)"

.PP
The event handler method reference definition\&. 
.PP
\fBParameters\fP
.RS 4
\fIevent\fP The event object to describe the event 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
