.TH "age.port.Port" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.port.Port
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBassign\fP (Events events)"
.br
.ti -1c
.RI "String \fBtitle\fP ()"
.br
.ti -1c
.RI "void \fBtitle\fP (String title)"
.br
.ti -1c
.RI "boolean \fBmaximized\fP ()"
.br
.ti -1c
.RI "void \fBmaximized\fP (boolean maximized)"
.br
.ti -1c
.RI "boolean \fBfullscreen\fP ()"
.br
.ti -1c
.RI "void \fBfullscreen\fP (boolean fullscreen)"
.br
.ti -1c
.RI "boolean \fBvisible\fP ()"
.br
.ti -1c
.RI "void \fBvisible\fP (boolean visible)"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "void \fBsize\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBRenderable\fP renderable)"
.br
.ti -1c
.RI "void \fBcreate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void age\&.port\&.Port\&.add (\fBRenderable\fP renderable)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.assign (Events events)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.create ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "boolean age\&.port\&.Port\&.fullscreen ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.fullscreen (boolean fullscreen)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "float age\&.port\&.Port\&.height ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "boolean age\&.port\&.Port\&.maximized ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.maximized (boolean maximized)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.render ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.size (float width, float height)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "String age\&.port\&.Port\&.title ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.title (String title)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "boolean age\&.port\&.Port\&.visible ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "void age\&.port\&.Port\&.visible (boolean visible)"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.
.SS "float age\&.port\&.Port\&.width ()"

.PP
Implemented in \fBage\&.port\&.jogl\&.JOGLPort\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
