.TH "age.event.Button" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.event.Button \- Enumeration of Pointer Buttons\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNONE\fP"
.br
.RI "Literal representing 'No Button'\&. "
.ti -1c
.RI "\fBBTN1\fP"
.br
.RI "Literal representing 'Pointer Button 1'\&. "
.ti -1c
.RI "\fBBTN2\fP"
.br
.RI "Literal representing 'Pointer Button 2'\&. "
.ti -1c
.RI "\fBBTN3\fP"
.br
.RI "Literal representing 'Pointer Button 3'\&. "
.ti -1c
.RI "\fBBTN4\fP"
.br
.RI "Literal representing 'Pointer Button 4'\&. "
.ti -1c
.RI "\fBBTN5\fP"
.br
.RI "Literal representing 'Pointer Button 5'\&. "
.ti -1c
.RI "\fBBTN6\fP"
.br
.RI "Literal representing 'Pointer Button 6'\&. "
.ti -1c
.RI "\fBBTN7\fP"
.br
.RI "Literal representing 'Pointer Button 7'\&. "
.ti -1c
.RI "\fBBTN8\fP"
.br
.RI "Literal representing 'Pointer Button 8'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enumeration of Pointer Buttons\&. 
.SH "Member Data Documentation"
.PP 
.SS "age\&.event\&.Button\&.BTN1"

.PP
Literal representing 'Pointer Button 1'\&. 
.SS "age\&.event\&.Button\&.BTN2"

.PP
Literal representing 'Pointer Button 2'\&. 
.SS "age\&.event\&.Button\&.BTN3"

.PP
Literal representing 'Pointer Button 3'\&. 
.SS "age\&.event\&.Button\&.BTN4"

.PP
Literal representing 'Pointer Button 4'\&. 
.SS "age\&.event\&.Button\&.BTN5"

.PP
Literal representing 'Pointer Button 5'\&. 
.SS "age\&.event\&.Button\&.BTN6"

.PP
Literal representing 'Pointer Button 6'\&. 
.SS "age\&.event\&.Button\&.BTN7"

.PP
Literal representing 'Pointer Button 7'\&. 
.SS "age\&.event\&.Button\&.BTN8"

.PP
Literal representing 'Pointer Button 8'\&. 
.SS "age\&.event\&.Button\&.NONE"

.PP
Literal representing 'No Button'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
