.TH "age.AGEException" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.AGEException
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGEException\fP ()"
.br
.ti -1c
.RI "\fBAGEException\fP (Throwable cause)"
.br
.ti -1c
.RI "\fBAGEException\fP (String message)"
.br
.ti -1c
.RI "\fBAGEException\fP (String message, Throwable cause)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.AGEException\&.AGEException ()"

.SS "age\&.AGEException\&.AGEException (Throwable cause)"

.SS "age\&.AGEException\&.AGEException (String message)"

.SS "age\&.AGEException\&.AGEException (String message, Throwable cause)"

.SH "Member Data Documentation"
.PP 
.SS "final long age\&.AGEException\&.serialVersionUID = 1L\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
