.TH "age.port.jogl.JOGLRenderListener" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
age.port.jogl.JOGLRenderListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits GLEventListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJOGLRenderListener\fP (\fBJOGLPort\fP \fBport\fP)"
.br
.ti -1c
.RI "void \fBinit\fP (GLAutoDrawable drawable)"
.br
.ti -1c
.RI "void \fBreshape\fP (GLAutoDrawable drawable, int x, int y, int width, int height)"
.br
.ti -1c
.RI "void \fBdisplay\fP (GLAutoDrawable drawable)"
.br
.ti -1c
.RI "void \fBdispose\fP (GLAutoDrawable drawable)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final \fBJOGLPort\fP \fBport\fP"
.br
.ti -1c
.RI "final \fBJOGLGraphics\fP \fBgraphics\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "age\&.port\&.jogl\&.JOGLRenderListener\&.JOGLRenderListener (\fBJOGLPort\fP port)"

.SH "Member Function Documentation"
.PP 
.SS "void age\&.port\&.jogl\&.JOGLRenderListener\&.display (GLAutoDrawable drawable)"

.SS "void age\&.port\&.jogl\&.JOGLRenderListener\&.dispose (GLAutoDrawable drawable)"

.SS "void age\&.port\&.jogl\&.JOGLRenderListener\&.init (GLAutoDrawable drawable)"

.SS "void age\&.port\&.jogl\&.JOGLRenderListener\&.reshape (GLAutoDrawable drawable, int x, int y, int width, int height)"

.SH "Member Data Documentation"
.PP 
.SS "final \fBJOGLGraphics\fP age\&.port\&.jogl\&.JOGLRenderListener\&.graphics\fC [private]\fP"

.SS "final \fBJOGLPort\fP age\&.port\&.jogl\&.JOGLRenderListener\&.port\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
