.TH "d:/GIT/repos/ODE/age/age/task Directory Reference" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
d:/GIT/repos/ODE/age/age/task Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTask\&.java\fP"
.br
.ti -1c
.RI "file \fBTasks\&.java\fP"
.br
.in -1c
