.TH "D:/GIT/repos/ODE/age/age/event/Handler.java" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/GIT/repos/ODE/age/age/event/Handler.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBage\&.event\&.Handler\fP"
.br
.RI "Interface to define an event handler method reference\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBage\&.event\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
