.TH "D:/GIT/repos/ODE/age/age/log/Log.java" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/GIT/repos/ODE/age/age/log/Log.java
.SH SYNOPSIS
.br
.PP
\fCimport java\&.io\&.File;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBage\&.log\&.Log\fP"
.br
.RI "Class that provides configurable Logging capabilities\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBage\&.log\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
