.TH "d:/GIT/repos/ODE/age/age/gui/Widgets.java" 3 "Version 1" "ODE Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
d:/GIT/repos/ODE/age/age/gui/Widgets.java
.SH SYNOPSIS
.br
.PP
\fCimport age\&.event\&.Events;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBage\&.gui\&.Widgets\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBage\&.gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ODE Framework from the source code\&.
